### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samrosecruz**
Adds this article to Required Reading

https://louderthanten.com/coax/design-machines

### CODE REVIEW

**Comment by samrosecruz** [comment]
@rstacruz mehehe

**Comment by victorsolis** [comment]
Sabi ko lagay sa tuktok eh

**Comment by samrosecruz** [comment]
AHAHA AYY

**Comment by victorsolis** [comment]
Hiwalay mo na section lol. As in sya yung una. Bold and shit.

**Comment by rstacruz** [comment]
> #### How to name pull requests
> The complete beginners guide on naming your pull requests with a helpful and meaningful name
>
> 1. 😋  _yolo bitches_

**Pull request merged**
