### PR TITLE
React Redux

### PR DESCRIPTION
**Pull request by akosipc**

### CODE REVIEW

**Comment by rickdtrick** [comment]
Lets add a folder for containers that handles multiple containers?
Like the layouts folder in rails

**Comment by rstacruz** [comment]
Also I think you should call it categorized per `feature`, not per `component`. Essentially what you want is something like this, right:

```js
react/
  conversations/
    components/
    containers/

  video_calling/
    components/
    containers/

  appointments/
    components/
    containers/

  shared/
    components/
    containers/
```

**Comment by rstacruz** [comment]
Suggestion: if you have one reducer per feature, I think it'd be nice to document the use of [reduce-reducers](https://duckduckgo.com/?q=reduce-reducers&atb=v31-6__&ia=software) or redux.combineReducers() :)

**Comment by rstacruz** [comment]
Also, use `js` highlighting for code:

    ```js
    function xyz () { ... }
    ```

**Comment by rstacruz** [comment]
Got a question here:

> - Containers are smart components. They do data-fetching and pass it to components.
> - Components are dumb

Wtih redux, every component is technically a dumb component. Data fetching and actions are done outside the component. Is this distinction useful in the case of react+redux? @victor

**Comment by rstacruz** [comment]
Merging for now, but let's also document the file naming convention.

**Comment by rstacruz** [comment]
Great work. Thank you for your contribution. 💚

**Comment by rstacruz** [comment]
My suggestions:

- Don't suggest `react-saga` or `react-promise`. thunk is enough. I don't like react-promise because it encourages you to discard errors and not provide loading states.

- Since a lot of this is derived from https://github.com/airbnb/javascript/tree/master/react - it should probably be linked.

- How about [a React-friendly RSCSS variant](https://medium.com/@mik01aj/rscss-77043f4fafb1)? This means:

  - Components are named exactly like react classes (ie: `.ShoppingCart` vs `.shopping-cart`)
  - If you can, put CSS in the same directory as components too

**Pull request merged**
